### ISSUE TITLE
Image re-downloading

### ISSUE THREAD

**Issue by almereyda** [libresh/compose-known#1]
I can upload images to known

```
root@rancher:/srv/docker-state/known-yalamerde# ls data/*/*/*/*/*
data/1/9/a/b/19ab6c6098a717fd062b0bb519dcd9ec.data  data/6/1/6/5/61656405a5a23108e83ad33716b1eb72.file
data/1/9/a/b/19ab6c6098a717fd062b0bb519dcd9ec.file  data/7/3/4/e/734e5e8f6198f4a9338a40ead9917bdc.data
data/2/6/3/0/263025d51886a5f18db60f9b2051fc93.data  data/7/3/4/e/734e5e8f6198f4a9338a40ead9917bdc.file
data/2/6/3/0/263025d51886a5f18db60f9b2051fc93.file  data/9/d/6/e/9d6e9975ade8a179fb3333da9bcb5557.data
data/6/1/6/5/61656405a5a23108e83ad33716b1eb72.data  data/9/d/6/e/9d6e9975ade8a179fb3333da9bcb5557.file
```

but cannot download them again. `docker-compose logs` shows

```
known-yalamerde-web_1 | 172.17.0.5 - - [22/Oct/2015:20:29:30 +0000] "GET /file/61656405a5a23108e83ad33716b1eb72/thumb.j
pg HTTP/1.1" 404 200 "https://y.te.gs/profile/almereyda" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36"
```

while I'm serving `known` via `docker-gen`. See associated [gist](https://gist.github.com/almereyda/7bb32a6d57d3c1ac37ca) for `docker-compose.yml` and `nginx.conf`. (Could also move the other snippets there.)

Ideas where the lock could be?
Obviously these requests never reach the app container, yet some transformation in `nginx.conf` is wrong?

**Comment by pierreozoux** [comment]
Should be fixed with: https://github.com/indiehosters/known/commit/0532c5885ccba934c124fb293d1bce336a333eb2

reopen if necessary
