### ISSUE TITLE
Ship Let's Encrypt with Known

### ISSUE THREAD

**Issue by paulcmal** [libresh/compose-known#10]
Let's encrypt is still n beta at the moment but it's already quite usable to provide free certificates.

How about shipping it with Known to have out of the box TLS support? It should remain optional though encouraged, as some people will use their own certificates or won't need any (in a local test environment).

One limitation: the amount of certs you can create (per user and per IP) is limited at the moment, so we should encourage people blindly/repeatedly testing the app or moving it across servers to reuse the same certificates (and not try to create new ones every time).

**Comment by pierreozoux** [comment]
I do run this behind a TLS offloader.
I agree with you that it si a nice to have.

How could we make it easy to have best of both world?

We could have an env variable "BEHIND_PROXY", if set to true, load nginx conf, if not, load nginx-ssl conf.
Adn if you load nginx-ssl.conf, it would check for the presence of cert, if not present, it will kindly ask letsencrypt for a new cert.

Does it sound reasonable to you?

I'd be happy to accept this kind of PR, but the code has to be simple.

**Comment by paulcmal** [comment]
> We could have an env variable "BEHIND_PROXY", if set to true, load nginx conf, if not, load nginx-ssl conf.

Agreed, but how about HTTPS_ENABLED? That's more explicit than "BEHIND_PROXY"?

Also, if TLS is enabled then we need to know the hostname used so that we can attach the volume /etc/letsencrypt/DOMAIN to our container. As I pointed out in #11, we need the domain used for the Known instance anyway. Do you see any inconvenience using hostname?

**Comment by pierreozoux** [comment]
I'll close this issue, I prefer to keep this project focused on delivering a good known behind a proxy than an average known for everything.
Let's encrypt is part of the haproxy setup.
