### ISSUE TITLE
Making nginx.conf IPv6- and HSTS-ready

### ISSUE THREAD

**Issue by paulcmal** [libresh/compose-known#11]
Hi,

I see two minor pitfalls with the current nginx.conf:
1. "listen 80" does not allow to listen on IPv6
2. nginx serves Known on all domains/addresses pointing to the container (i.e. there is only one server block, which doesn't have a server_name)
3. server blocks (except the default server) should be in seperate files for maintainability

My proposals:
1. "listen 80" should be replaced by "listen [::]:80"
2. HSTS configuration should only affect the domain used by the Known setup and not all domains pointing (willingly or not) to port 80/443 on our container. I would argue that serving our content only on one address in general is preferable, if only for SEO.
In addition to the current server block (which should have a server_name, maybe matching HOSTNAME?), there should be a second one without a server_name using "listen [::]:80 ipv6only=off default_server; listen [::]:443 ipv6only=off default_server" with the same TLS parameters but with HSTS disabled. It would still display HTTPS warning messages, but could not accidentally add HSTS headers to the wrong domain. This second block should either serve a static page or redirect to the "valid" URL (return 302 DOMAIN$request_uri).
Please note that the change proposed in 1) does not include ipv6only=off as this parameter can only be used once per port, in the first server block running on this port. I believe it's better for readability to have ipv6only and default_server in the same server block, in the beginning of the file.
3. nginx.conf should import server blocks located in a seperate folder, and all server blocks except the default landing/redirect should be relocated there

---

Any feedback on this? Sorry for not submitting patches/PRs, I don't really have a proper dev environment (or Internet access, for what it's worth) lately.

**Comment by pierreozoux** [comment]
Hi!

And thanks for your time analyzing all of this. (and sorry for the delay of response)

I'd say that this is the docker deployment. And in the docker world, containers are made to run behind a load-balancer/TLS offloader and so on.
So this setup is made for that. (I use it this way in conjunction with [haproxy](https://github.com/indiehosters/haproxy))
I guess what you are asking would be a nice to have, but should be in a different project.

I hope you understand, and I'll close the related issues #10 and #12 .
