### ISSUE TITLE
Redirect to/from www.

### ISSUE THREAD

**Issue by paulcmal** [libresh/compose-known#12]
As pointed out in #11, I'd rather have only one URL serving the content.

Many people who are new to the web tend to argue over whether to use www or not. I think both should be accessible, one redirecting to the other.

For example, http://www.cmal.info, http://cmal.info and https://www.cmal.info all redirect to https://cmal.info. This can be done in done in one server block:

```
server {
    server_name blah blouh blih;
    listen [::]:80;
    listen [::]:443 ssl;

    ssl_certificate...

    location / {
        return 301 https://DOMAIN$request_uri
    }
}
```

A permanent redirection seems appropriate to me in this case.

Whether to redirect to or from www. depends on the domain chosen by the user. The setup script should just check the domain used and create a new server block accordingly (see #11 3)).

**Comment by pierreozoux** [comment]
HAProxy setup does alreay exactly that :)
