### ISSUE TITLE
Twitter, Soundcloud and Facebook plugins are gone.

### ISSUE THREAD

**Issue by almereyda** [libresh/compose-known#17]
After upgrading, the plugins page doesn't know the Twitter, Soundcloud and Facebook plugins anymore, and only the hosted Convoy service is being offered. Hence, all IndieWeb'bish independence is gone.

How can I restore their functionality?

**Comment by almereyda** [comment]
@pierreozoux Without these plugins, Known rendered useless for me. Do you have any advice?

**Comment by pierreozoux** [comment]
Sorry :)

**Comment by almereyda** [comment]
Ah https://github.com/indiehosters/docker-known/blob/master/Dockerfile#L3-L27

Grazie di Firenze
