### ISSUE TITLE
Twitter connection

### ISSUE THREAD

**Issue by almereyda** [libresh/compose-known#2]
Yeah, I am lucky, want to try out everything!

```
Warning: substr_count(): Empty substring in /var/www/html/IdnoPlugins/Twitter/Main.php on line 79

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/IdnoPlugins/Twitter/Main.php:79) in /var/www/html/Idno/Common/Page.php on line 519
```

What am I missing?

**Comment by almereyda** [comment]
Obviously nothing:

https://twitter.com/almereyda/status/657297419370156032

**Comment by pierreozoux** [comment]
Ok, I'll take a look :)

Can we close this one?

**Comment by pierreozoux** [comment]
Should be fixed with: https://github.com/indiehosters/known/commit/0532c5885ccba934c124fb293d1bce336a333eb2

reopen if necessary
