### ISSUE TITLE
Backups lack data folder tarball

### ISSUE THREAD

**Issue by almereyda** [libresh/compose-known#4]
Would be nice to keep that stuff, too, don't you think @pierreozoux ?

**Comment by pierreozoux** [comment]
The purpose of the BACKUP script is to prepare the full folder to be ready to be backed up.

Personally, I use duplicity to copy this folder to another server.

But what do you think? If you want, we can discuss the package format at: https://github.com/indiehosters/applications/
(i'm actually thinking to get closer and closer to yunohost package form to be one day compatible) What do you think?

**Comment by almereyda** [comment]
Interoperability is actually a real concern in hosting diverse distributed applications. Migration format was a thing at #oslabs15. Actually Sandstorm, Cozy and Yunohost follow a similar pattern, yet use different approaches. I have created a [new issue](https://github.com/indiehosters/applications/issues/106).

**Comment by pierreozoux** [comment]
Ok, I close this and move to the new issue.
