### ISSUE TITLE
Facebook didn't catch the URL setting

### ISSUE THREAD

**Issue by almereyda** [libresh/compose-known#6]
In my fork, I am using a custom URL setting.

https://github.com/indiehosters/known/compare/master...allmende:master

Look what happens when syndicating to Facebook:

https://www.facebook.com/10208267317499843/posts/10208267322459967?_rdr=p

**Comment by pierreozoux** [comment]
Should be fixed with: https://github.com/indiehosters/known/commit/0532c5885ccba934c124fb293d1bce336a333eb2

reopen if necessary
