### ISSUE TITLE
Markdown Plugin

### ISSUE THREAD

**Issue by almereyda** [libresh/compose-known#7]
It doesn't seem to bother

> https://y.te.gs/2015/checked-into-thinkfarm

to render the Markdown string into HTML.

How can I debug this?

**Comment by almereyda** [comment]
Markdown at least works in the Post post type

> https://y.te.gs/2015/i-never-knew-what-load-average-means-do-you

**Comment by pierreozoux** [comment]
I think this is the normal behaviour of Markdown plugin.
